server:
  port: 80
spring:
  application:
    name: order-consumer


eureka:
  instance:
    hostname: localhost
    # 修改服务显示名称
    instance-id: order01
    # 显示ip信息
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
